server.port=8090
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Route vers PharmacyStock-Service
spring.cloud.gateway.routes[0].id=pharmacy-stock-service
spring.cloud.gateway.routes[0].uri=lb://PHARMACYSTOCK-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/stock/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1


spring.cloud.gateway.routes[1].id=order-prescription-service
spring.cloud.gateway.routes[1].uri=lb://ORDER-PRESCRIPTION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Route vers User-Service
spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**, /users/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1



spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true